variable "name" {}
variable "rg_name" {}
variable "image_id" {}
variable "network_interface_id" {}
variable "location" {}
variable "zone" {}
variable "azurerm_network_security_group_id" {}
variable "dns_record_gp_name" {}
variable "env" {}